export const SALES_SAVED = "SALES_SAVED";
export const SALES_REQUEST = "SALES_REQUEST";
export const SALES_SUCCESS = "SALES_SUCCESS";
export const SALES_FAILURE = "SALES_FAILURE";
export const SALES_DELETE_REQUEST = "SALES_DELETE_REQUEST";
